### Ниже продемонстрировано использование библиотеки numpy, операции над ndim массивами, некоторые векторные операции и статистика 
#### Первым делом импорт

In [26]:
import numpy as np
from numpy import random as rn

#### Одномерные массивы

In [27]:
#начнем с небольшого количества одномерных массивов
tArray = [2,4,6] 
b = np.array(tArray) # создание numpy ndarray из уже существующего массива
c = np.zeros(23) #создание 1-мерного массива из 23 нулей 
d = np.ones(5) #массив из 5 единиц
print("b: ", b) 
print("c: ", c)
print("d: ", d) 

b:  [2 4 6]
c:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
d:  [1. 1. 1. 1. 1.]


#### Двумерные массивы

In [28]:
#теперь создадим двумерные массивы и посмотрим, что вообще они умеют
matrix = np.arange(1,10).reshape(3,3) #делаем массив с числами от 1 до 9 и потом меняем его форму на матрицу 3 на 3
print("first matrix: \n", matrix) 


first matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
tensor = np.ones(27).reshape(3,3,3)  #тензор, или же 3д массив 3x3x3 с единицами
for i in range(tensor.shape[0]): #идем по каждой оси(путешествуем в другие измерения xD), начиная с 0
    for j in range(tensor.shape[1]): 
        for k in range(tensor.shape[2]): 
            tensor[i,j,k] *= rn.randint(1,10) #просто умножим на любое число от 1 до 10
print("tensor: \n", tensor)  #получившаяся матрица 

tensor: 
 [[[5. 3. 6.]
  [1. 9. 6.]
  [4. 2. 6.]]

 [[9. 2. 2.]
  [2. 8. 4.]
  [9. 7. 6.]]

 [[3. 6. 3.]
  [2. 3. 2.]
  [1. 1. 4.]]]


In [30]:
uMatrix = np.eye(3) #единичная матрица 
print("\nunity matrix: \n", uMatrix) 


unity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Атрибуты матриц

In [31]:
print("c shape: ", c.shape) #размерность

c shape:  (23,)


In [32]:
print("c type: ", c.dtype) #тип хранимых данных

c type:  float64


In [33]:
print("matrix shape:", matrix.shape) #аналогично

matrix shape: (3, 3)


In [34]:
print("matrix type: ", matrix.dtype)

matrix type:  int64


In [35]:
n = np.arange(2,30).reshape(2,14) #сделаем матрицу 2 на 14
print(n.shape) 

(2, 14)


In [36]:
print(np.transpose(n).shape) # если ее транспонировать, форма изменится 

(14, 2)


#### Индексирование и срезы

In [37]:
print(tensor)

[[[5. 3. 6.]
  [1. 9. 6.]
  [4. 2. 6.]]

 [[9. 2. 2.]
  [2. 8. 4.]
  [9. 7. 6.]]

 [[3. 6. 3.]
  [2. 3. 2.]
  [1. 1. 4.]]]


In [38]:
randomElem = tensor[rn.randint(0,3)] #возьмем какой-нибудь рандомный элемент из нашего рандомного тензора)) 
print("random element: \n", randomElem) 
print(tensor[0][1:3]) #возьмем срез с 1 по 2 элементы включительно 

random element: 
 [[5. 3. 6.]
 [1. 9. 6.]
 [4. 2. 6.]]
[[1. 9. 6.]
 [4. 2. 6.]]


In [39]:
print(tensor[1,2]) 
print(tensor[1][2]) #одно и то же, но тут создается копия подмассива, что менее эффективно 

[9. 7. 6.]
[9. 7. 6.]


In [40]:
print(tensor[:3, 1, 1:3])#для каждой матрицы с 0 по 3 возьмем первую строку и из нее элементы с 1 по 2

[[9. 6.]
 [8. 4.]
 [3. 2.]]


### Еще немного срезов

In [41]:
arr = np.array([
    [ 0,  1,  2,  3],
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43]
])
print("arr: \n", arr)

arr: 
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [42]:
print(arr[(2,3)]) #возьмем элемент из 2 строки 3 столбца(с нуля)

23


In [43]:
print(arr[[2,3]]) #возьмем массив элементов со 2 по 3 строки

[[20 21 22 23]
 [30 31 32 33]]


In [44]:
print(arr[2:4,2]) #из строк со 2 по 4 (невкл) символы с индексом 2

[22 32]


#### Операции над массивами и немного статистики

In [45]:
x = np.arange(0,10) 
y = np.arange(10,20) 
r1 = x + y 
r2 = x * y 
r3 = y // 3 
r4 = np.hstack((x,y)) 
r5 = np.vstack((x,y)) 
print(x, "\n", y, "\n")

[0 1 2 3 4 5 6 7 8 9] 
 [10 11 12 13 14 15 16 17 18 19] 



In [46]:
print("addition: \n",r1) 
print("multiplication: \n", r2) 
print("division: ", r3)
print("stacking horizontal: ", r4) 
print("stacking vertical: ", r5) 

addition: 
 [10 12 14 16 18 20 22 24 26 28]
multiplication: 
 [  0  11  24  39  56  75  96 119 144 171]
division:  [3 3 4 4 4 5 5 5 6 6]
stacking horizontal:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
stacking vertical:  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [47]:
np.hsplit(r5,2) #разделим на две матрицы горизонтально - по столбцам

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [48]:
np.vsplit(r5,2) #тоже разделим на две матрицы, но по строкам

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [49]:
print(np.mean(r5)) #среднее арифметическое

9.5


In [50]:
print(r5.min()) #минимум
print(r5.max()) #максимум

0
19
